const architectureMockData = {
  levels: ["Project View", "Repository View", "Module View", "Service View", "API View", "Database View"],
  flows: {
    login: ["frontend", "loginRoute", "authController", "authService", "authModule", "userRepository", "postgres"],
    checkout: ["frontend", "apiGateway", "billingService", "queue", "worker", "postgres"],
    session: ["frontend", "apiGateway", "authService", "redis"],
  },
  nodes: [
    { id: "frontend", type: "architecture", position: { x: 80, y: 80 }, data: { label: "Web App", type: "Frontend", layer: "Presentation Layer", lang: "TypeScript", framework: "React", visibility: "Public", description: "Primary browser application and design-system shell.", path: "/src/app", files: ["src/main.jsx", "CodeScopeApp.jsx"], apis: ["POST /login"], services: ["AuthService"] } },
    { id: "backend", type: "architecture", position: { x: 80, y: 260 }, data: { label: "Backend App", type: "Backend", layer: "Business Layer", lang: "TypeScript", framework: "Node", visibility: "Internal", description: "Server-side application boundary that hosts controllers, services, and workers.", path: "/src/server", files: ["server.ts", "app.module.ts"], apis: ["REST API"], services: ["AuthService", "BillingService"] } },
    { id: "identityModule", type: "architecture", position: { x: 360, y: -90 }, data: { label: "Identity Module", type: "Module", layer: "Business Layer", lang: "TypeScript", framework: "NestJS", visibility: "Internal", description: "Module boundary that groups authentication routes, controllers, and service providers.", path: "/src/modules/identity", files: ["modules/identity/index.ts", "modules/identity/providers.ts"], apis: ["POST /api/login"], services: ["AuthService", "Auth Module"] } },
    { id: "loginRoute", type: "architecture", position: { x: 360, y: 40 }, data: { label: "Login API", type: "Route", layer: "Presentation Layer", lang: "TypeScript", framework: "Express", visibility: "Public", description: "HTTP route for user login requests.", path: "/src/routes/login.ts", files: ["routes/login.ts"], apis: ["POST /api/login"], services: ["AuthService"] } },
    { id: "apiGateway", type: "architecture", position: { x: 360, y: 150 }, data: { label: "API Gateway", type: "API Gateway", layer: "Infrastructure Layer", lang: "Go", framework: "Gin", visibility: "Public", description: "Routes external traffic to domain services.", path: "/gateway", files: ["gateway/main.go"], apis: ["/*"], services: ["AuthService", "BillingService"] } },
    { id: "authController", type: "architecture", position: { x: 640, y: 40 }, data: { label: "AuthController", type: "Controller", layer: "Business Layer", lang: "TypeScript", framework: "NestJS", visibility: "Internal", description: "Validates login payloads and delegates authentication.", path: "/src/controllers/auth.ts", files: ["controllers/auth.ts"], apis: ["POST /api/login"], services: ["AuthService"] } },
    { id: "authService", type: "architecture", position: { x: 920, y: 90 }, data: { label: "AuthService", type: "Service", layer: "Business Layer", lang: "TypeScript", framework: "Node", visibility: "Internal", description: "Owns credential checks, session creation, and token issuing.", path: "/src/services/auth.ts", files: ["services/auth.ts", "services/token.ts"], apis: ["POST /api/login"], services: ["UserRepository", "Redis"] } },
    { id: "authModule", type: "architecture", position: { x: 920, y: -70 }, data: { label: "Auth Module", type: "Auth", layer: "Business Layer", lang: "TypeScript", framework: "JWT", visibility: "Internal", description: "Authentication boundary for JWT signing, guards, and session policy.", path: "/src/auth", files: ["auth/guards.ts", "auth/jwt.ts"], apis: ["POST /api/login"], services: ["AuthService"] } },
    { id: "billingService", type: "architecture", position: { x: 920, y: 250 }, data: { label: "BillingService", type: "Service", layer: "Business Layer", lang: "Go", framework: "gRPC", visibility: "Internal", description: "Handles checkout orchestration and payment workflows.", path: "/services/billing", files: ["billing/service.go"], apis: ["POST /checkout"], services: ["MessageQueue", "ExternalStripe"] } },
    { id: "userRepository", type: "architecture", position: { x: 1200, y: 90 }, data: { label: "UserRepository", type: "Repository", layer: "Data Layer", lang: "TypeScript", framework: "Prisma", visibility: "Internal", description: "Data access boundary for users and credentials.", path: "/src/repositories/user.ts", files: ["repositories/user.ts"], apis: [], services: ["Postgres"] } },
    { id: "postgres", type: "architecture", position: { x: 1480, y: 90 }, data: { label: "PostgreSQL", type: "Database", layer: "Data Layer", lang: "SQL", framework: "PostgreSQL", visibility: "Private", description: "Primary relational datastore.", path: "db:postgres", files: ["schema.sql"], apis: [], services: [] } },
    { id: "redis", type: "architecture", position: { x: 1200, y: 220 }, data: { label: "Redis Sessions", type: "Redis Cache", layer: "Data Layer", lang: "Redis", framework: "Redis", visibility: "Private", description: "Caches session and rate-limit state.", path: "cache:sessions", files: ["infra/redis.yml"], apis: [], services: [] } },
    { id: "queue", type: "architecture", position: { x: 1200, y: 360 }, data: { label: "Billing Events", type: "Message Queue", layer: "Infrastructure Layer", lang: "AMQP", framework: "RabbitMQ", visibility: "Private", description: "Asynchronous event channel for billing and worker tasks.", path: "queue:billing", files: ["infra/rabbitmq.yml"], apis: [], services: ["BillingWorker"] } },
    { id: "worker", type: "architecture", position: { x: 1480, y: 360 }, data: { label: "BillingWorker", type: "Worker", layer: "Infrastructure Layer", lang: "Go", framework: "Worker", visibility: "Private", description: "Consumes billing events and persists results.", path: "/workers/billing", files: ["workers/billing.go"], apis: [], services: ["PostgreSQL"] } },
    { id: "stripe", type: "architecture", position: { x: 1200, y: 520 }, data: { label: "Stripe", type: "External APIs", layer: "External Services", lang: "HTTPS", framework: "REST", visibility: "External", description: "External payment processor integration.", path: "external:stripe", files: ["integrations/stripe.ts"], apis: ["Stripe API"], services: [] } },
    { id: "config", type: "architecture", position: { x: 640, y: 310 }, data: { label: "Runtime Config", type: "Configuration", layer: "Infrastructure Layer", lang: "YAML", framework: "Docker", visibility: "Private", description: "Environment-specific runtime configuration.", path: "/config", files: ["docker-compose.yml", ".env"], apis: [], services: ["API Gateway"] } },
    { id: "env", type: "architecture", position: { x: 360, y: 320 }, data: { label: "Environment", type: "Environment", layer: "Infrastructure Layer", lang: "ENV", framework: "Runtime", visibility: "Private", description: "Placeholder for runtime secrets and environment variables.", path: ".env", files: [".env.example"], apis: [], services: ["Runtime Config"] } },
    { id: "storage", type: "architecture", position: { x: 1480, y: 520 }, data: { label: "Object Storage", type: "Storage", layer: "External Services", lang: "S3", framework: "S3", visibility: "External", description: "Stores reports and generated artifacts.", path: "s3://reports", files: ["storage/client.ts"], apis: ["S3 API"], services: [] } },
    { id: "scheduler", type: "architecture", position: { x: 640, y: 470 }, data: { label: "Analysis Scheduler", type: "Scheduler", layer: "Infrastructure Layer", lang: "Python", framework: "Celery", visibility: "Private", description: "Schedules repository analysis jobs.", path: "/jobs/scheduler.py", files: ["jobs/scheduler.py"], apis: [], services: ["MessageQueue"] } },
  ],
  edges: [
    { id: "a1", source: "frontend", target: "loginRoute", label: "calls" },
    { id: "a2", source: "frontend", target: "apiGateway", label: "calls" },
    { id: "a2b", source: "backend", target: "authController", label: "imports" },
    { id: "a2c", source: "identityModule", target: "authController", label: "imports" },
    { id: "a3", source: "loginRoute", target: "authController", label: "triggers" },
    { id: "a4", source: "authController", target: "authService", label: "calls" },
    { id: "a4b", source: "authService", target: "authModule", label: "authenticates" },
    { id: "a5", source: "authService", target: "userRepository", label: "depends on" },
    { id: "a6", source: "userRepository", target: "postgres", label: "reads" },
    { id: "a7", source: "userRepository", target: "postgres", label: "writes" },
    { id: "a8", source: "authService", target: "redis", label: "caches" },
    { id: "a9", source: "apiGateway", target: "authService", label: "authenticates" },
    { id: "a10", source: "apiGateway", target: "billingService", label: "calls" },
    { id: "a11", source: "billingService", target: "queue", label: "publishes" },
    { id: "a12", source: "worker", target: "queue", label: "consumes" },
    { id: "a13", source: "worker", target: "postgres", label: "writes" },
    { id: "a14", source: "billingService", target: "stripe", label: "calls" },
    { id: "a15", source: "config", target: "apiGateway", label: "imports" },
    { id: "a15b", source: "env", target: "config", label: "depends on" },
    { id: "a16", source: "scheduler", target: "queue", label: "triggers" },
    { id: "a17", source: "worker", target: "storage", label: "stores" },
  ],
};


export { architectureMockData };

